### ISSUE TITLE
Lets add a few static routes for auth

### ISSUE THREAD

**Issue by ehsundar** [rehacktive/caffeine#21]
Now that we have JWT implemented here, I think we can add a few routes to achieve these:

* register new user (signup)
  - full name
  - username
  - password
* get a jwt with expire time
  - username
  - password
* refresh jwt
  - token (as header)

If you agreed, I would open a MR soon.

Please note that we need to sacrifice user model flexibility to implement a reliabe API. This flaw can be remedied in future MRs.

**Comment by rehacktive** [comment]
"Please note that we need to sacrifice user model flexibility to implement a reliabe API. This flaw can be remedied in future MRs." 

What you mean by this?

Anyway, user auth is an option, I'd prefer not to have specific endpoints integrated in Caffeine.
In my view, I imagine a different microservice with the routes you defined and a separate database, and the generated JWT (or the refreshed one) will work seamlessly in Caffeine, as long as the tokens are based on the same cert/key.

Thought?
