### ISSUE TITLE
client generation?

### ISSUE THREAD

**Issue by slangens1** [rehacktive/caffeine#5]
Great project!

I plan to use this eventually, but if i'm going to design a service, I need both client and server. I'd rather not have to spec out both if possible.

It'd be cool if you could generate a swagger or protobuf definition from existing data and schema. I'm sure that's a lot of work but it'd be much more powerful to have strictly typed objects in the client.

**Comment by rehacktive** [comment]
hello! thanks! 

Unfortunately I think the client side is a bit out of scope (especially tech like protobuf) - you can already use json schemas on "server-side" (in caffeine) and there are tools to Go struct from json schemas and similar, according to your need.

So I'm closing this issue.

**Comment by rehacktive** [comment]
btw @slangens1 swagger specs generation has been added.

**Comment by slangens1** [comment]
Sounds good to me!
