### ISSUE TITLE
File based database

### ISSUE THREAD

**Issue by ehsundar** [rehacktive/caffeine#8]
I want to develop a feature to use file system as data storage. It is similar to the mem implementation except that the data is persisted easily on disk. To be honest, I think pg is kinda overkill.

In terms of security (e.g. namespaces named like /test/../../../ssh.conf) we should prohibit names with slashes and dots. Although if caf is used inside a container (mounted directory) this problem won't be a valid concern anymore...

**Comment by ehsundar** [comment]
We'll have a base dir as the root of storage. then ns would be directories inside it. doc ids are filenames.

The only concern is that if we want to develop other features rather than simple keyval storage in the future (for example builtin user management and authorization) lack of relational db would be a serious challenge

**Comment by rehacktive** [comment]
I like the idea. I kinda did something like that ages ago as another project, but never had time to update it (https://github.com/rehacktive/kvod/) - you can have a look and either adapt it or grab some functions.

The security of the namespace is not a problem - the value is already matched with a regular expression with gorilla mux (/ns/{namespace:[a-zA-Z0-9]+}) so nothing like ../../ would ever match.

PS: thanks for the PR, gonna check it later and merge

**Comment by ehsundar** [comment]
Nice repo. I can surely use some of the codes there. I'll be back with anothre PR!

**Comment by rehacktive** [comment]
gonna close this since your work has been merged! thanks again
